/**
* This file was generated by scripts/make-models.js on 2023-06-14T18:18:10.946Z
* Do not edit this file manually.
*/

export const models = {
  "generateMessage": [
    {
      "name": "chat-bison-001",
      "version": "001",
      "displayName": "Chat Bison",
      "description": "Chat-optimized generative language model.",
      "inputTokenLimit": 4096,
      "outputTokenLimit": 1024,
      "temperature": 0.25,
      "topP": 0.95,
      "topK": 40
    }
  ],
  "generateText": [
    {
      "name": "text-bison-001",
      "version": "001",
      "displayName": "Text Bison",
      "description": "Model targeted for text generation.",
      "inputTokenLimit": 8196,
      "outputTokenLimit": 1024,
      "temperature": 0.7,
      "topP": 0.95,
      "topK": 40
    }
  ],
  "embedText": [
    {
      "name": "embedding-gecko-001",
      "version": "001",
      "displayName": "Embedding Gecko",
      "description": "Obtain a distributed representation of a text.",
      "inputTokenLimit": 1024,
      "outputTokenLimit": 1
    }
  ]
};