/**
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { Board, Schema } from "@google-labs/breadboard";
import Core from "@google-labs/core-kit";
import { PaLMKit } from "@google-labs/palm-kit";

const simplest = new Board({
  title: "The simplest LLM-based board",
  description:
    "This is as simple as it gets: the board takes a prompt as input and generates a response as output.",
  version: "0.0.2",
});
const core = simplest.addKit(Core);
const palm = simplest.addKit(PaLMKit);

const completion = palm.generateText();
core.secrets({ keys: ["PALM_KEY"] }).wire("PALM_KEY", completion);
simplest
  .input({
    $id: "prompt",
    schema: {
      type: "object",
      properties: {
        text: {
          type: "string",
          title: "Prompt",
          description: "The prompt to generate a completion for",
          examples: ["Tell me a fun story about playing with breadboards"],
        },
      },
      required: ["text"],
    } satisfies Schema,
  })
  .wire(
    "text",
    completion.wire(
      "completion->text",
      simplest.output({
        $id: "completion",
        schema: {
          type: "object",
          properties: {
            text: {
              type: "string",
              title: "Response",
              description: "The completion generated by the LLM",
            },
          },
          required: ["text"],
        },
      })
    )
  );

export default simplest;
