/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A schema for a BeginRendering message in the A2A streaming UI protocol. This message signals that the UI can now be rendered and provides initial root component and styling information.
 */
export interface BeginRenderingMessage {
  /**
   * The ID of the root component from which rendering should begin. This is a reference to a component instance by its unique ID.
   */
  root: string;
}
