/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A schema for a StreamHeader message in the A2A streaming UI protocol.
 */
export interface StreamHeaderMessage {
  /**
   * The version of the protocol.
   */
  version: string;
}
