import { base, recipe } from "@google-labs/breadboard";

import { starter } from "@google-labs/llm-starter";
import { core } from "@google-labs/core-kit";

/*
To run this: npx breadboard run createEmbedding.js --kit @google-labs/core-kit --kit @google-labs/llm-starter -i "{ \"api_inputs\": {
      \"bearer\": \"OPENAI_API_KEY\",
      \"application/json\": {
        \"input\":
          \"Hello, my name is Paul and I'm not a large language model. I'm a real boy.\",
        \"model\": \"text-embedding-ada-002\"
      }
    }
}"
*/

const metaData = {
  title: "Create Embedding",
  description: "Creates an embedding from OpenAI (Generated by OpenAPI recipe)",
  version: "0.0.3",
};

export default await recipe(() => {
  const input = base.input({ $id: "input" });

  return core.invoke({
    path: "../createEmbedding.json",
    ...input.api_inputs,
    ...starter.secrets({ keys: ["OPENAI_API_KEY"] }),
  });
}).serialize(metaData);
