/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @fileoverview Imperative implementation of the UI step.
 * A UI node is asset-like: it stores on-demand UI data (HTML, schemas,
 * function name) generated by `generate_new_ui`, providing context to
 * downstream Generate steps.
 */

import { Schema } from "@breadboard-ai/types";

export { invoke as default, describe };

type UIInputs = {
  "html-code"?: string;
  "input-schema"?: string;
  "callback-schema"?: string;
  "function-name"?: string;
  "dummy-input"?: string;
};

type UIOutputs = {
  context: { parts: { text: string }[]; role: string }[];
};

async function invoke(inputs: UIInputs): Promise<UIOutputs> {
  const htmlCode = inputs["html-code"] ?? "";
  const inputSchema = inputs["input-schema"] ?? "{}";
  const callbackSchema = inputs["callback-schema"] ?? "{}";
  const functionName = inputs["function-name"] ?? "";
  const dummyInput = inputs["dummy-input"] ?? "{}";

  const uiData = {
    htmlCode,
    inputSchema,
    callbackSchema,
    functionName,
    dummyInput,
  };

  return {
    context: [
      {
        parts: [{ text: JSON.stringify(uiData) }],
        role: "user",
      },
    ],
  };
}

type DescribeInputs = {
  inputs: UIInputs;
};

async function describe({ inputs }: DescribeInputs) {
  void inputs;
  return {
    inputSchema: {
      type: "object",
      properties: {
        "html-code": {
          type: "string",
          behavior: ["config"],
          title: "HTML Code",
          description: "The generated HTML code for this UI",
        },
        "input-schema": {
          type: "string",
          behavior: ["config"],
          title: "Input Schema",
          description: "JSON schema for the renderUI input argument",
        },
        "callback-schema": {
          type: "string",
          behavior: ["config"],
          title: "Callback Schema",
          description: "JSON schema for the callback argument",
        },
        "function-name": {
          type: "string",
          behavior: ["config", "hint-preview"],
          title: "Function Name",
          description: "The snake_case identifier for this UI function",
        },
        "dummy-input": {
          type: "string",
          behavior: ["config"],
          title: "Dummy Input",
          description: "A sample input payload for previewing the UI",
        },
      },
      additionalProperties: false,
    } satisfies Schema,
    outputSchema: {
      type: "object",
      properties: {
        context: {
          type: "array",
          items: { type: "object", behavior: ["llm-content"] },
          title: "Context out",
          behavior: ["main-port"],
        },
      },
      additionalProperties: false,
    } satisfies Schema,
    title: "UI",
    metadata: {
      icon: "web",
      tags: ["quick-access", "core", "ui"],
      order: 2,
    },
  };
}
