# Copyright 2026 Google LLC
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

import logging
from typing import Any, Callable

import httpx

from bees.pidgin import from_pidgin_string
from bees.protocols.session import SessionConfiguration
from opal_backend.local.backend_client_impl import HttpBackendClient

logger = logging.getLogger("bees.runners.adapters.image")


class ImageAdapter:
    """Adapter for direct image generation via Gemini REST API.

    Supports:
    - Multimodal prompts via pidgin file references (``<file src="..." />``)
      resolved into ``inlineData`` parts for subject grounding.
    - Runtime configuration via ``options`` (aspect_ratio, image_size,
      person_generation) mapped into ``generationConfig``.
    """

    async def generate(
        self,
        config: SessionConfiguration,
        slug: str | None,
        log_event: Callable[[dict[str, Any]], Any],
        backend: HttpBackendClient,
        api_key: str,
        options: dict[str, Any] | None = None,
    ) -> None:
        # 1. Combine text segments to form prompt string.
        prompt_parts = []
        for segment in config.segments:
            seg_type = segment.get("type")
            if seg_type == "text":
                text = segment.get("text", "")
                if text:
                    prompt_parts.append(text)
            elif seg_type == "input":
                content = segment.get("content", {})
                for part in content.get("parts", []):
                    if "text" in part:
                        prompt_parts.append(part["text"])

        prompt = "\n".join(prompt_parts).strip()

        # Fallback to objective.md if prompt is empty.
        if not prompt and config.ticket_dir:
            objective_path = config.ticket_dir / "objective.md"
            if objective_path.is_file():
                prompt = objective_path.read_text(encoding="utf-8").strip()

        if not prompt:
            raise ValueError("Direct image generation failed: Empty prompt / objective")

        # 2. Resolve pidgin file references → multimodal content.
        #    from_pidgin_string returns {"parts": [...], "role": "user"} where
        #    parts can include text AND inlineData (for <file src="..." /> tags).
        translated = await from_pidgin_string(prompt, config.file_system)
        if isinstance(translated, dict) and "$error" in translated:
            raise ValueError(translated["$error"])

        resolved_model = config.model or "gemini-3.1-flash-image-preview"

        # 3. Build generationConfig from options.
        generation_config = _build_generation_config(options)

        body: dict[str, Any] = {
            "contents": [translated],
        }
        if generation_config:
            body["generationConfig"] = generation_config

        send_request_event = {
            "sendRequest": {
                "body": {
                    "model": resolved_model,
                    "contents": body["contents"],
                    **({"generationConfig": generation_config} if generation_config else {}),
                }
            }
        }
        await log_event(send_request_event)

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{resolved_model}:generateContent?key={api_key}"
        async with httpx.AsyncClient(timeout=httpx.Timeout(300.0)) as client:
            res = await client.post(url, json=body, headers={"Content-Type": "application/json"})
            if res.status_code != 200:
                raise ValueError(f"Gemini image generation failed ({res.status_code}): {res.text}")
            data = res.json()

        candidates = data.get("candidates", [])
        if not candidates:
            raise ValueError("No candidates returned from Gemini image generation")

        parts = candidates[0].get("content", {}).get("parts", [])
        if not parts:
            raise ValueError("No parts returned from Gemini image generation")

        intermediate_files = []
        for i, part in enumerate(parts):
            if "inlineData" in part:
                file_name = f"{slug}/image_{i}.png" if slug else f"image_{i}.png"
                saved_path = config.file_system.add_part(part, file_name=file_name)
                if isinstance(saved_path, dict) and "$error" in saved_path:
                    raise ValueError(saved_path["$error"])
                intermediate_files.append({
                    "path": file_name,
                    "content": part
                })

        if not intermediate_files:
            raise ValueError("No images were generated by the model")

        complete_event = {
            "complete": {
                "result": {
                    "success": True,
                    "outcomes": {
                        "parts": [{"text": f"Generated {len(intermediate_files)} image(s)."}]
                    },
                    "intermediate": intermediate_files
                }
            }
        }
        await log_event(complete_event)


# ---------------------------------------------------------------------------
# Options → generationConfig mapping
# ---------------------------------------------------------------------------

# Gemini image generation supports responseModalities and image config
# within generationConfig.  See:
# https://ai.google.dev/gemini-api/docs/image-generation



def _build_generation_config(
    options: dict[str, Any] | None,
) -> dict[str, Any] | None:
    """Map user-facing options into Gemini generationConfig.

    Returns None if no options require config overrides.
    """
    if not options:
        return None

    image_config: dict[str, Any] = {}

    aspect_ratio = options.get("aspect_ratio")
    if aspect_ratio:
        image_config["aspectRatio"] = aspect_ratio

    image_size = options.get("image_size")
    if image_size:
        image_config["imageSize"] = str(image_size)

    person_generation = options.get("person_generation")
    if person_generation:
        image_config["personGeneration"] = person_generation

    if not image_config:
        return None

    return {
        "responseModalities": ["TEXT", "IMAGE"],
        "imageConfig": image_config,
    }
