# Copyright 2026 Google LLC
# SPDX-License-Identifier: Apache-2.0

from __future__ import annotations

from typing import Any, Callable

import httpx

from bees.pidgin import from_pidgin_string
from bees.protocols.session import SessionConfiguration
from opal_backend.local.backend_client_impl import HttpBackendClient


class MusicAdapter:
    """Adapter for direct music generation via Gemini REST API (Lyria 3 Pro)."""

    async def generate(
        self,
        config: SessionConfiguration,
        slug: str | None,
        log_event: Callable[[dict[str, Any]], Any],
        backend: HttpBackendClient,
        api_key: str,
        options: dict[str, Any] | None = None,
    ) -> None:
        # Combine text segments to form prompt
        prompt_parts = []
        for segment in config.segments:
            seg_type = segment.get("type")
            if seg_type == "text":
                text = segment.get("text", "")
                if text:
                    prompt_parts.append(text)
            elif seg_type == "input":
                content = segment.get("content", {})
                for part in content.get("parts", []):
                    if "text" in part:
                        prompt_parts.append(part["text"])

        prompt = "\n".join(prompt_parts).strip()

        # Fallback to objective.md if prompt is empty
        if not prompt and config.ticket_dir:
            objective_path = config.ticket_dir / "objective.md"
            if objective_path.is_file():
                prompt = objective_path.read_text(encoding="utf-8").strip()

        if not prompt:
            raise ValueError("Direct music generation failed: Empty prompt / objective")

        # Translate pidgin references (resolving files/images)
        translated = await from_pidgin_string(prompt, config.file_system)
        if isinstance(translated, dict) and "$error" in translated:
            raise ValueError(translated["$error"])

        resolved_model = config.model or "lyria-3-pro-preview"

        body: dict[str, Any] = {
            "contents": [translated],
            "generationConfig": {
                "responseModalities": ["AUDIO"]
            }
        }

        send_request_event = {
            "sendRequest": {
                "body": {
                    "model": resolved_model,
                    "contents": body["contents"],
                    "generationConfig": body["generationConfig"],
                }
            }
        }
        await log_event(send_request_event)

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{resolved_model}:generateContent?key={api_key}"
        async with httpx.AsyncClient(timeout=httpx.Timeout(300.0)) as client:
            res = await client.post(url, json=body, headers={"Content-Type": "application/json"})
            if res.status_code != 200:
                raise ValueError(f"Gemini music generation failed ({res.status_code}): {res.text}")
            data = res.json()

        candidates = data.get("candidates", [])
        if not candidates:
            raise ValueError("No candidates returned from Gemini music generation")

        parts = candidates[0].get("content", {}).get("parts", [])
        if not parts:
            raise ValueError("No parts returned from Gemini music generation")

        intermediate_files = []
        for i, part in enumerate(parts):
            if "inlineData" in part:
                file_name = f"{slug}/audio_{i}.wav" if slug else f"audio_{i}.wav"
                part["inlineData"]["mimeType"] = "audio/wav"

                saved_path = config.file_system.add_part(part, file_name=file_name)
                if isinstance(saved_path, dict) and "$error" in saved_path:
                    raise ValueError(saved_path["$error"])
                intermediate_files.append({
                    "path": file_name,
                    "content": part
                })

        if not intermediate_files:
            raise ValueError("No music was generated by the model")

        final_path = intermediate_files[0]["path"]
        complete_event = {
            "complete": {
                "result": {
                    "success": True,
                    "outcomes": {
                        "parts": [{"text": f"Result written to {final_path}"}]
                    },
                    "intermediate": intermediate_files
                }
            }
        }
        await log_event(complete_event)
