/**
 * @license
 * Copyright 2023 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  board,
  enumeration,
  input,
  output,
} from "@breadboard-ai/build";
import { geminiText } from "@google-labs/gemini-kit";

const prompt = input({
  type: "string",
  title: "Prompt",
  description: "The prompt to generate a completion for",
  examples: ["Tell me a fun story about playing with breadboards"],
});

const model = input({
  type: enumeration("gemini-1.5-flash-latest", "gemini-1.5-pro-latest")
});

const llmResponse = geminiText({ model, text: prompt });

export default board({
  title: "The simplest LLM-based board",
  description:
    "This board is as simple as it gets: takes text as input and invokes Gemini to generate a text response as output.",
  version: "0.1.0",
  inputs: { model, prompt },
  outputs: {
    response: output(llmResponse.outputs.text, {
      title: "Response",
      description: "The completion generated by the LLM",
    }),
  }
});