/**
 * @license
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { readFile, writeFile } from "fs/promises";
import { join } from "path";

const source = join(import.meta.dirname, "environment.d.ts");
const destination = join(import.meta.dirname, "type-declarations.ts");

async function generate() {
  const declarations = await readFile(source, "utf-8");
  const asString = `/**
 * @license
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

// THIS FILE IS GENERATED BY update-type-declarations.ts
// DO NOT EDIT DIRECTLY

export const typeDeclarations = \`
${declarations}\`
`;
  await writeFile(destination, asString);
}

await generate();
