import {
  board,
  input,
  output,
} from "@breadboard-ai/build";

import { code } from "@google-labs/core-kit";

export const text = input({
  type: "string",
  title: "text",
  description: "The text to return",
  examples: ["Hello World!!"],
});

const message = code(
  {
    $id: "text",
    $metadata: {
      title: "text",
      description: "my message to return",
    },
    text,
  },
  {
    message: "string",
  },
  ({ text }) => {
    return { message: text };
  }
);

const messageOutput = output(message.outputs.message, {
  title: "Response",
  description: "The completion generated by the LLM",
})

export default board({
  title: "Blank Board",
  description:
    "A blank board. Use it to start a new board",
  version: "0.1.0",
  inputs: { text },
  outputs: { messageOutput }
});