name: rendering
title: Testing Updates
description: A playbook to test updates.

steps:
  main:
    title: Infinite chat that listens for updates.
    objective: >
      As soon as you start, call the chat_request_user_input function with an
      empty prompt and wait for the context_update. You are using this function
      to receive context updates, not to ask the user questions.

      Once the context update is received, write a poem about it, and then call
      chat_request_user_input again. Repeat forever.
    tags: ["testing"]
    functions: ["chat.*"]
    watch_events:
      - type: test_update
