service: connections

runtime: nodejs22

instance_class: F1

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  CONNECTIONS_FILE: "secrets/secrets.json"
  ALLOWED_ORIGINS: ""
