#!/usr/bin/env node

/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Scaffolds a new hive directory with minimal configuration.
 *
 * Usage:
 *   node scripts/create-hive.mjs <path>
 *   npm run create-hive -w packages/bees -- <path>
 */

import { mkdir, writeFile, access } from "node:fs/promises";
import { resolve, basename, relative } from "node:path";

const SYSTEM_YAML = (title) => `\
# Hive system configuration.
#
# title       — Display name for this hive instance.
# description — Short summary shown in UI.
# root        — Template name to auto-boot at startup. Leave blank to start idle.
title: ${title}
description: ""
`;

const TEMPLATES_YAML = `\
# Ticket templates — define agent task types here.
#
# Each entry needs at minimum: name, title, objective.
# See docs/patterns.md for the full field reference.

- name: researcher
  title: Researcher
  description: Deeply researches a given topic
  objective: >
    Your job is to deeply research the following topic:

    {{system.context}}

  functions:
    - system.*
  tags:
    - worker
`;

const GITIGNORE = `\
# Runtime state — generated by the box, not tracked in version control.
tickets/
logs/
mutations/
.env
.mcp-tokens/
`;

async function main() {
  const target = process.argv[2];

  if (!target) {
    console.error("Usage: node scripts/create-hive.mjs <path>");
    console.error("  e.g. node scripts/create-hive.mjs ~/hives/my-project");
    process.exit(1);
  }

  const root = resolve(target);

  // Guard against overwriting an existing hive.
  try {
    await access(resolve(root, "config", "SYSTEM.yaml"));
    console.error(`Error: ${root} already contains a hive (config/SYSTEM.yaml exists).`);
    process.exit(1);
  } catch {
    // Expected — directory doesn't exist yet.
  }

  const title = basename(root);

  // Create directory structure.
  const dirs = [
    "config/hooks",
    "skills",
    "tickets",
    "logs",
    "mutations",
  ];

  for (const dir of dirs) {
    await mkdir(resolve(root, dir), { recursive: true });
  }

  // Write configuration files.
  await writeFile(resolve(root, "config", "SYSTEM.yaml"), SYSTEM_YAML(title));
  await writeFile(resolve(root, "config", "TEMPLATES.yaml"), TEMPLATES_YAML);
  await writeFile(resolve(root, ".gitignore"), GITIGNORE);

  // Print summary.
  const rel = relative(process.cwd(), root);
  const displayPath = rel.startsWith("..") ? root : rel;

  console.log("");
  console.log(`  🐝 Hive created: ${displayPath}`);
  console.log("");
  console.log("  Structure:");
  for (const dir of dirs) {
    console.log(`    ${dir}/`);
  }
  console.log("    config/SYSTEM.yaml");
  console.log("    config/TEMPLATES.yaml");
  console.log("    .gitignore");
  console.log("");
  console.log("  To start the box:");
  console.log(`    BEES_HIVE_DIR=${displayPath} npm run dev:box -w bees`);
  console.log("");
}

main();
