import { base } from "@google-labs/breadboard";
import { core } from "@google-labs/core-kit";
import { templates } from "@google-labs/template-kit";

const inputs = base.input({
  $id: "query",
  schema: {
    type: "object",
    properties: {
      year: {
        title: "year",
        type: "number",
        description: "The data for year",
        default: new Date().getFullYear().toString(),
      },
      countryCode: {
        title: "countryCode",
        type: "string",
        description: "The data for countryCode",
        enum: [
          "AD",
          "AL",
          "AM",
          "AR",
          "AT",
          "AU",
          "AX",
          "BA",
          "BB",
          "BE",
          "BG",
          "BJ",
          "BO",
          "BR",
          "BS",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CH",
          "CL",
          "CN",
          "CO",
          "CR",
          "CU",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FO",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GG",
          "GI",
          "GL",
          "GM",
          "GR",
          "GT",
          "GY",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IM",
          "IN",
          "IS",
          "IT",
          "JE",
          "JM",
          "JP",
          "KE",
          "KG",
          "KH",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LI",
          "LK",
          "LT",
          "LU",
          "LV",
          "MA",
          "MC",
          "MD",
          "ME",
          "MK",
          "MT",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PK",
          "PL",
          "PR",
          "PT",
          "PY",
          "RO",
          "RS",
          "RU",
          "RW",
        ],
        default: "US",
      },
    },
    required: ["year", "countryCode"],
  },
});

const urlTemplate = templates.urlTemplate({
  $id: "urlTemplate",
  template: "https://date.nager.at/api/v3/PublicHolidays/{year}/{countryCode}",
  year: inputs.year,
  countryCode: inputs.countryCode,
});

const fetchUrl = core.fetch({
  $id: "fetch",
  method: "GET",
  url: urlTemplate.url,
});

const output = base.output({
  dates: fetchUrl.response,
  schema: {
    type: "array",
    items: {
      type: "object",
      properties: {
        date: {
          type: "string",
          format: "date",
        },
        localName: {
          type: "string",
        },
        name: {
          type: "string",
        },
        countryCode: {
          type: "string",
        },
        fixed: {
          type: "boolean",
        },
        global: {
          type: "boolean",
        },
        counties: {
          type: "array",
          items: {
            type: "string",
          },
        },
        launchYear: {
          type: "integer",
        },
        type: {
          type: "array",
          items: {
            type: "string",
          },
        },
      },
    },
  },
});

export default await output.serialize({
  title: "Nager Date Public Holidays API",
  description: "Get the public holidays for the Nager Date API",
  version: "0.0.1",
});
