/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

export const galleryItems = [
  {
    title: "Book Recs",
    description:
      "Get book recommendations and discover your next favorite read",
    carouselImg: "/styles/landing/images/carousel/book.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/book-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/book-mobile.jpg",
    url: "drive:/1q9jXXdALFT8ddP6eQkzmkIbcmX_CT323",
    bgCol: "#B0B0A9",
    txtCol: "#2E2E27",
  },
  {
    title: "Business Profiler",
    description: "An accurate glimpse of how the internet sees your business",
    carouselImg: "/styles/landing/images/carousel/business.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/business-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/business-mobile.jpg",
    url: "drive:/1DutpRERwbgRyL7AmqXkjQwigdkPZyZlo",
    bgCol: "#E5B3B3",
    txtCol: "#442222",
  },
  {
    title: "City Builder",
    description: "Create a game concept with AI-generated visuals",
    carouselImg: "/styles/landing/images/carousel/city.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/city-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/city-mobile.jpg",
    url: "drive:/1IpNhTmLUITyHlYTFUjsjko7gnpeEnJmt",
    bgCol: "#DFD5CB",
    txtCol: "#442222",
  },
  {
    title: "Fashion Stylist",
    description: "Create a weather appropriate outfit for a specific occasion",
    carouselImg: "/styles/landing/images/carousel/fashion.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/fashion-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/fashion-mobile.jpg",
    url: "drive:/1dHEOTpzi9oqE4s9o4qhF1ty8zZhOAc81",
    bgCol: "#E6D3C6",
    txtCol: "#553925",
  },
  {
    title: "Generated Playlist",
    description: "Create a playlist for your current mood with YouTube links",
    carouselImg: "/styles/landing/images/carousel/music.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/music-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/music-mobile.jpg",
    url: "drive:/1qzorj2p07fwkSaQvsYIEKVsUtZwirUkP",
    bgCol: "#FFDCBE",
    txtCol: "#593C1E",
  },
  {
    title: "Learning with YouTube",
    description: "Turn your YouTube video into a quiz to help you learn",
    carouselImg: "/styles/landing/images/carousel/learn.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/learn-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/learn-mobile.jpg",
    url: "drive:/1bKYzqve-9MHL9X7N4GKDhw1EwS-An49W",
    bgCol: "#FFB9B7",
    txtCol: "#2E2E27",
  },
  {
    title: "Product Research",
    description:
      "Get a personalized report for the product you want to research",
    carouselImg: "/styles/landing/images/carousel/product.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/product-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/product-mobile.jpg",
    url: "drive:/1uCJbBuHb4lYnHZ4TnvVz6SAqpnkFefpi",
    bgCol: "#FFC5AB",
    txtCol: "#2E2E27",
  },
  {
    title: "Social Media Post",
    description: "Create a social media post for your business",
    carouselImg: "/styles/landing/images/carousel/social.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/social-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/social-mobile.jpg",
    url: "drive:/1gVJ_rbivnOCQGEs6KQQOezE6ZgWLDdr7",
    bgCol: "#FCF399",
    txtCol: "#000000",
  },
  {
    title: "Video Marketer",
    description: "Creates AI video ads with your product and target audience",
    carouselImg: "/styles/landing/images/carousel/video.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/video-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/video-mobile.jpg",
    url: "drive:/1xZquMjAG5zj8Uu5z-F6FXSVx3LSCMoTW",
    bgCol: "#9EEFFD",
    txtCol: "#001F24",
  },
  {
    title: "Blog Post Writer",
    description: "Researches a topic and writes a blog post about it",
    carouselImg: "/styles/landing/images/carousel/blog.jpg",
    desktopImg: "/styles/landing/images/carousel/modal/blog-desktop.jpg",
    mobileImg: "/styles/landing/images/carousel/modal/blog-mobile.jpg",
    url: "drive:/1Rvxpl1F6k9mxnk4a2eYLOZhrFXsrJ2B8",
    bgCol: "#B7D37D",
    txtCol: "#364517",
  },
];
