runtime: nodejs22

instance_class: F2

handlers:
  - url: /boards.*
    script: auto

  - url: /(.*\..+)$
    static_files: dist/client/\1
    upload: dist/client/(.*\..+)$

build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: ""
