name: Tests for Breadboard in an isolated environment
on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 21.x
          - 20.x
          - 19.x
          - 18.x
        npm-version:
          - 10.x
          - 9.x
          - 8.x
          - 7.x
          - 6.x
        exclude:
          - node-version: 19.x
            npm-version: 9.x
          - node-version: 19.x
            npm-version: 10.x
        commands:
          - name: cli mermaid
            script: |
              set -ev
              npm install -g @google-labs/breadboard-cli
              wget https://raw.githubusercontent.com/ExaDev-io/breadboard-samples/develop/samples/Breadboard%20Walkthrough/src/hello-world/board.json -O board.json

              npx breadboard mermaid board.json

          - name: cli run
            script: |
              set -ev
              npm install -g @google-labs/breadboard-cli
              wget https://raw.githubusercontent.com/ExaDev-io/breadboard-samples/develop/samples/Breadboard%20Walkthrough/src/hello-world/board.json -O board.json

              npx breadboard run board.json -i "{\"message\": \"Hello World\"}"

          - name: init board
            script: |
              set -ev
              npm init @google-labs/breadboard test
              cd test
              npm pkg get scripts || cat package.json
              npm install
              npm run test

          - name: init kit
            script: |
              set -ev
              npm init @google-labs/breadboard-kit test
              cd test
              npm pkg get scripts || cat package.json
              npm install
              npm run test
    name: Node ${{ matrix.node-version }} NPM ${{ matrix.npm-version }} - ${{ matrix.commands.name }}
    steps:
      - uses: actions/checkout@main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm install -g npm@${{ matrix.npm-version }}
      - name: Run command
        run: ${{ matrix.commands.script }}
